### ISSUE TITLE
Summon does not set fluid type causing exception

### ISSUE THREAD

**Issue by coolacid** [TheRoBrit/Moo-Fluids#20]
When trying to "/summon EntityFluidCow" the following error happens:

```
[08/4/2015 12:49:31 PM] net.minecraft.util.ReportedException: Saving entity NBT
[08/4/2015 12:49:31 PM] 	at net.minecraft.entity.Entity.func_70109_d(Entity.java:1359) ~[sa.class:?]
[08/4/2015 12:49:31 PM] 	at net.minecraft.entity.Entity.func_70039_c(Entity.java:1298) ~[sa.class:?]
[08/4/2015 12:49:31 PM] 	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:346) [aqk.class:?]
[08/4/2015 12:49:31 PM] 	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:197) [aqk.class:?]
[08/4/2015 12:49:31 PM] 	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:256) [ms.class:?]
[08/4/2015 12:49:31 PM] 	at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:302) [ms.class:?]
[08/4/2015 12:49:32 PM] 	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:809) [mt.class:?]
[08/4/2015 12:49:32 PM] 	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318) [MinecraftServer.class:?]
[08/4/2015 12:49:32 PM] 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:569) [MinecraftServer.class:?]
[08/4/2015 12:49:32 PM] 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
[08/4/2015 12:49:32 PM] 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
[08/4/2015 12:49:32 PM] 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[08/4/2015 12:49:32 PM] Caused by: java.lang.NullPointerException
[08/4/2015 12:49:32 PM] 	at com.robrit.moofluids.common.entity.EntityFluidCow.func_70014_b(EntityFluidCow.java:313) ~[EntityFluidCow.class:?]
[08/4/2015 12:49:32 PM] 	at net.minecraft.entity.Entity.func_70109_d(Entity.java:1342) ~[sa.class:?]
[08/4/2015 12:49:32 PM] 	... 11 more
```

I suspect the /summon command doesn't actually set a random fluid and when MC tries to save the state of the cow, it balks.

**Comment by zortag** [comment]
I have the same issue on cow spawning while i'm going around, usually in new chunks
