### ISSUE TITLE
Integer is too big for 4 bytes

### ISSUE THREAD

**Issue by sharkck** [TheRoBrit/Moo-Fluids#37]
After about a day of uptime, my server just continually starts spamming the message below.  A server reboot always seems to fix it.  Depending on when I catch it, my server log files get really huge from where this is constantly spammed.  I havent noticed any issues in-game aside from the constant console spam.

`Jul 08, 2016 11:45:43 AM io.netty.channel.embedded.EmbeddedChannel recordException
WARNING: More than one exception was raised. Will report only the first one and log others.
io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Integer is too big for 4 bytes
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
        at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644)
        at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698)
        at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688)
        at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717)
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893)
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239)
        at cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAllAround(SimpleNetworkWrapper.java:210)
        at com.jdlogic.ranchablefluidcows.ranchable.RanchableFC.sendPacket(RanchableFC.java:82)
        at com.jdlogic.ranchablefluidcows.ranchable.RanchableFC.updateClient(RanchableFC.java:74)
        at com.jdlogic.ranchablefluidcows.ranchable.RanchableFC.ranch(RanchableFC.java:44)
        at powercrystals.minefactoryreloaded.tile.machine.TileEntityRancher.activateMachine(TileEntityRancher.java:77)
        at powercrystals.minefactoryreloaded.tile.base.TileEntityFactoryPowered.func_145845_h(TileEntityFactoryPowered.java:103)
        at net.minecraft.world.World.func_72939_s(World.java:1939)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
        at fastcraft.at.a(F:978)
        at fastcraft.H.aq(F:36)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.IllegalArgumentException: Integer is too big for 4 bytes
        at org.apache.commons.lang3.Validate.isTrue(Validate.java:106)
        at cpw.mods.fml.common.network.ByteBufUtils.writeVarInt(ByteBufUtils.java:100)
        at com.jdlogic.ranchablefluidcows.network.CowUpdateMessage.toBytes(CowUpdateMessage.java:37)
        at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:11)
        at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:7)
        at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:51)
        at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67)
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)
        ... 22 more`

**Comment by sharkck** [comment]
Any luck on this?
