### ISSUE TITLE
1.10.2 - Server Crash NPE

### ISSUE THREAD

**Issue by Dyonovan** [TheRoBrit/Moo-Fluids#46]
Caused by: java.lang.NullPointerException
	at com.robrit.moofluids.common.entity.EntityFluidCow.writeSpawnData(EntityFluidCow.java:350)

Full Crash log: https://gist.github.com/Dyonovan/0ecc9ebed2e82fa55105b130478e2fe7

**Comment by Zeevian** [comment]
I can second this, just happened to me 3 times back to back on log in.  Once the chunk loads, it immediately crashes.  Different mods, but same path
[crash-2017-03-27_01.39.26-server.txt](https://github.com/TheRoBrit/Moo-Fluids/files/871557/crash-2017-03-27_01.39.26-server.txt)

**Comment by Lycanic** [comment]
Reporting another instance. Purging the possible cows somewhat (examples included things which are gases, IC2 coolant in hot/cold (and same for steam) and fluid cyanite which was written in a different format to everything else) seems to have stopped the crashes.

I have the same line as the first poster in the crash logs, I'm playing on a custom pack which has a lot of mods smooshed together (so if there's a chance for interference, it's probably my fault).

**Comment by cauliflower69** [comment]
I can confirm the same thing. We just updated to the latest foolcraft and are getting the exact same issue.

**Comment by WinterGrave** [comment]
I get same thing on my server:
https://pastebin.com/iJh1JH3A

**Comment by lilti** [comment]
I am having the same issue. I am playing the Foolcraft pack and can no longer log into my world. It's the same error:

Caused by: java.lang.NullPointerException
 at com.robrit.moofluids.common.entity.EntityFluidCow.writeSpawnData(EntityFluidCow.java:350)

Is there a fix coming for this? I would like to avoid deleting my fluid cows if possible.

**Comment by Lycanic** [comment]
So, to temporarily fix this issue you need to stop cows spawning - I think setting the "Fluid Cow Global Spawn Rate" to 0 should do it.

You then need to remove the problem cow - I do this either via chunk deletion or region deletion. In saves/name/region is where you'll do this. Chunks will require NBTExplorer to delete chunks within each r.n.m.mca, where each r.n.m is a 512 block square region (16 chunks). If you're exploring afar you can probably be okay with just deleting the relevant region (eg if you were going in the +x direction you can just delete the r. with the highest first number). You should be able to find your coords in the crash log, but these won't be the same as the problem cow so you may have to delete some areas around you.

**Comment by lilti** [comment]
In my situation it definitely occurred in chunks that were already generated as I am right outside my base and the surrounding area is well explored. Unfortunately for me, deleting the area around me would basically be like deleting my whole save and starting over. I'm still holding out hope for an update, otherwise I will just have to remove the mod.
